### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/osm-stats-api#14]
Lets document the readme with all of the routes available.

**Comment by smit1678** [comment]
Yes, detailed API docs are on the main osm-stats repo documentation: https://github.com/AmericanRedCross/osm-stats/blob/master/documentation/API.md. I added the endpoints and links in the README here in https://github.com/AmericanRedCross/osm-stats-api/commit/0d366602dd153c8022d6a724b3b5a42406026aed. These all endpoints for the leaderboard, user page, and partner page views. Post here if there is anything that is unclear.
