### ISSUE TITLE
CORS policy

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/osm-stats-api#25]
@kamicut @maxgrossman can  you guys add a CORS policy to the stats api please.

**Comment by kamicut** [comment]
@dalekunce The API already has CORS enabled [here](https://github.com/AmericanRedCross/osm-stats-api/blob/master/index.js#L8). Are you getting CORS errors?

**Comment by dalekunce** [comment]
fixed it, had to the with http vs https on the site.
