### ISSUE TITLE
CORS issue with top-users call

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/osm-stats-api#29]
clicking "Users" under Activity on the partner pages gives this error (via @smit1678)
```
Failed to load http://osm-stats-api.azurewebsites.net/top-users/jpmc: 
Redirect from 'http://osm-stats-api.azurewebsites.net/top-users/jpmc' 
to 'https://osm-stats-api.azurewebsites.net/top-users/jpmc' has been 
blocked by CORS policy: No 'Access-Control-Allow-Origin' header is 
present on the requested resource. Origin 'http://www.missingmaps.org' 
is therefore not allowed access.
```

@dalekunce

**Comment by smit1678** [comment]
I think there is two solutions to this: 

1. Flip a switch (assuming there is one) on the Microsoft side of things to allow requests from http
2. Put https on `www.missingmaps.org`. Since Github Pages doesn't serve content as https when using a custom domain. 

not sure if there are other solutions at the moment.

**Comment by smit1678** [comment]
Ok, this is now fixed. Apparently missingmaps.org is available behind https, so I switched the config domain to https, https://github.com/MissingMaps/partners/commit/1fec5dcf8ccaf2c61b630122efac133f26d6bd05, and then also fixed an http url within the user stats call: https://github.com/MissingMaps/partners/commit/6324d9679341354e81735037f6d1250e73ae5d47. 

This is working on both http and https pages: 

- http://www.missingmaps.org/partners/salesforce/
- https://www.missingmaps.org/partners/salesforce/

**Comment by danbjoseph** [comment]
thanks for figuring this out!

**Comment by danbjoseph** [comment]
MissingMaps/partners#129

**Comment by dalekunce** [comment]
Thanks @smit1678 good work.

**Comment by mojodna** [comment]
Whoa, that's super cool. It looks like GitHub + Fastly are now using Let's Encrypt to provide SSL for GitHub pages. 🌶
