### ISSUE TITLE
Backfilling

### ISSUE THREAD

**Issue by lesserj** [AmericanRedCross/osm-stats-api#30]
Hey @mojodna,

I'm running an instance of osm-stats-api and osm-stats-workers for a fork of the HOT Tasking Manager.  I'm looking to backfill data from about March until now.  I'm looking at your backfill instructions and you reference some externally generated files.  I'm trying to figure out how to generate those files from overpass-turbo.  Do you have saved overpass queries you could share, or have any pointers how to build the backfill data?

Thanks!

**Comment by mojodna** [comment]
The tables referenced in [`BACKFILL.md`](https://github.com/AmericanRedCross/osm-stats-api/blob/master/BACKFILL.md) were produced by generating historical geometries and measuring / counting them using OSMesa.

**Comment by lesserj** [comment]
Thanks.  That's good information.  I'll look into OSMesa.
